(()=>{'use strict';
const canvas=document.querySelector('#gl'),photo=document.querySelector('#portrait'),button=document.querySelector('#start'),again=document.querySelector('#again'),ui=document.querySelector('.ui'),status=document.querySelector('#status');
const gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false,powerPreference:'high-performance'});
if(!gl){status.textContent='Для частиц требуется WebGL2. Проверьте аппаратное ускорение браузера.';photo.classList.add('show');button.disabled=true;return}
const vert=`#version 300 es
precision highp float;
in vec3 aHeart;in vec2 aTarget;in vec3 aColor;in float aSeed;
uniform float uTime,uPhase,uAspect,uScale,uRatio,uPointerX,uPointerY;out vec3 vColor;out float vAlpha;
float ease(float x){x=clamp(x,0.,1.);return x*x*(3.-2.*x);} float hash(float x){return fract(sin(x*127.1)*43758.5453);}
void main(){float t=uPhase;float beat=1.+.028*sin(uTime*3.8)+.015*sin(uTime*7.6);vec3 h=aHeart*beat;float d=length(h.xy-vec2(uPointerX,uPointerY));h.xy+=normalize(h.xy-vec2(uPointerX,uPointerY)+.0001)*.025*exp(-d*8.)*sin(uTime*4.+aSeed*10.);
float delay=.12*hash(aSeed*12.);float crush=ease((t-.04)/.105);float launch=ease((t-.13-delay)/.19);float assemble=ease((t-.46-delay*.5)/.36);float portraitX=aTarget.x*uScale;float portraitY=aTarget.y*uScale*uRatio;vec3 dest=vec3(portraitX,portraitY,0.);
vec3 compressed=h*mix(1.,.32,crush);float a=atan(h.y,h.x)+6.2831*(3.2*launch+hash(aSeed*22.));float r=mix(length(compressed.xy),.16+1.35*hash(aSeed*19.)+(.35*sin(aSeed*200.)),launch);float spiral=a+3.8*launch+2.6*sin(aSeed*3.);vec3 vortex=vec3(cos(spiral)*r,sin(spiral)*r,.35*sin(a+uTime*3.)+.75*(hash(aSeed*8.)-.5));vec3 p=mix(compressed,vortex,launch);p=mix(p,dest,assemble);p.z+=.09*(1.-assemble)*sin(uTime*2.+aSeed*30.);p.xy+=assemble*(1.-ease((t-.87)/.12))*.004*sin(uTime*2.+aSeed*43.);
float perspective=2.4/(2.4-p.z*.30);gl_Position=vec4(p.x*perspective/uAspect,p.y*perspective,0.,1.);gl_PointSize=clamp((1.5+1.4*hash(aSeed*88.))*perspective*(1.+.3*sin(uTime*2.+aSeed*32.)),1.,5.)*min(2.,uAspect*1.3);vColor=mix(vec3(1.,.16,.38)+.25*vec3(hash(aSeed*8.),hash(aSeed*4.),hash(aSeed*14.)),aColor,ease((t-.53)/.22));vAlpha=(.48+.5*hash(aSeed*55.))*(1.-ease((t-.9)/.1));}`;
const frag=`#version 300 es
precision highp float;in vec3 vColor;in float vAlpha;out vec4 outColor;void main(){vec2 q=gl_PointCoord-.5;float r=length(q);float a=smoothstep(.5,.05,r)*vAlpha;if(a<.005)discard;outColor=vec4(vColor,a);}`;
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
let program;try{program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vert));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,frag));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program))}catch(e){status.textContent='Не удалось запустить графическую сцену: '+e.message;photo.classList.add('show');return}
gl.useProgram(program);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);let n=0,ratio=1,scale=1;const u={};for(const name of ['uTime','uPhase','uAspect','uScale','uRatio','uPointerX','uPointerY'])u[name]=gl.getUniformLocation(program,name);
function heart(t,fill){const x=16*Math.pow(Math.sin(t),3)/18;const y=(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))/18;return[x*fill,y*fill]}
function init(img){const source=document.createElement('canvas'),w=360,h=Math.round(360*img.naturalHeight/img.naturalWidth);source.width=w;source.height=h;const ctx=source.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h).data;const step=1;const count=w*h;const data=new Float32Array(count*9);let k=0;for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const j=(y*w+x)*4,i=k*9;const theta=Math.random()*Math.PI*2;const fill=Math.sqrt(Math.random());const hp=heart(theta,fill);data[i]=hp[0]*.66;data[i+1]=hp[1]*.66;data[i+2]=(Math.random()-.5)*.22;data[i+3]=(x+.5)/w*2-1;data[i+4]=1-(y+.5)/h*2;let light=.55+Math.random()*.48;data[i+5]=Math.pow(pixels[j]/255,1.12)*light;data[i+6]=Math.pow(pixels[j+1]/255,1.12)*light;data[i+7]=Math.pow(pixels[j+2]/255,1.12)*light;data[i+8]=Math.random()*999.;k++}n=k;ratio=h/w;const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);const stride=9*4;for(const [name,size,offset] of [['aHeart',3,0],['aTarget',2,12],['aColor',3,20],['aSeed',1,32]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,stride,offset)}resize();requestAnimationFrame(draw)}
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);gl.viewport(0,0,canvas.width,canvas.height);const a=canvas.width/canvas.height;scale=Math.min(.80/ratio,.77*a);gl.uniform1f(u.uAspect,a);gl.uniform1f(u.uScale,scale);gl.uniform1f(u.uRatio,ratio)}addEventListener('resize',resize);
let startAt=0,phase=0,playing=false,finished=false,mx=4,my=4;const duration=9000;
function draw(ms){const sec=ms*.001;if(playing){phase=Math.min(1,(ms-startAt)/duration);if(phase>.78&&!photo.classList.contains('show'))photo.classList.add('show');if(phase>=1){playing=false;finished=true;ui.classList.remove('reveal');ui.classList.add('finished');again.hidden=false}}gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform1f(u.uTime,sec);gl.uniform1f(u.uPhase,phase);gl.uniform1f(u.uPointerX,mx);gl.uniform1f(u.uPointerY,my);if(!finished)gl.drawArrays(gl.POINTS,0,n);requestAnimationFrame(draw)}
canvas.addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth*2-1)*innerWidth/innerHeight;my=1-e.clientY/innerHeight*2});canvas.addEventListener('pointerleave',()=>{mx=4;my=4});
let audio;function sound(){try{audio?.close();audio=new (window.AudioContext||window.webkitAudioContext)();const now=audio.currentTime;const notes=[164.81,246.94,329.63,493.88,659.25];notes.forEach((f,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),filter=audio.createBiquadFilter();osc.type='sine';osc.frequency.setValueAtTime(f,now+i*.35);filter.type='lowpass';filter.frequency.value=1050;gain.gain.setValueAtTime(0,now+i*.35);gain.gain.linearRampToValueAtTime(.035,now+i*.35+.25);gain.gain.exponentialRampToValueAtTime(.001,now+i*.35+2.5);osc.connect(filter).connect(gain).connect(audio.destination);osc.start(now+i*.35);osc.stop(now+i*.35+2.6)})}catch(e){}}
function start(){if(playing)return;finished=false;phase=0;photo.classList.remove('show');ui.classList.remove('finished');ui.classList.add('reveal');again.hidden=true;playing=true;startAt=performance.now();sound()}button.onclick=start;again.onclick=start;canvas.onclick=()=>{if(!playing&&!finished)start()};if(photo.complete&&photo.naturalWidth)init(photo);else{photo.onload=()=>init(photo);photo.onerror=()=>{status.textContent='Файл assets/portrait.jpg не найден';button.disabled=true}};
})();
